gamemode_bloodbath:
  is_enabled: true
  smart_scp_selection: true
  max_scp_count: 3
  remaining_broadcast: '%count Class-D remaining!'
  remaining_broadcast_dur: 5
  end_round_broadcast: '%user is the winner!'
  end_round_broadcast_dur: 15
gamemode_juggernaut:
  is_enabled: true
  juggernaut_health: 10000
  juggernaut_inventory: []
gamemode_outbreak:
  is_enabled: true
  all_deaths_make_zombies: true
  alphas_break_locked_doors: true
  smart_scp_selection: true
  infection_chance: 80
  max_alpha_count: 3
  alpha_zombie_health: 3000
  wait_time: 60
  end_round_broadcast: '%user is the winner!'
  end_round_broadcast_dur: 15